version: 0.0
os: linux
files:
  - source: perfexcrm/
    destination: /var/www/html/
    owner: www-data
hooks:
  BeforeInstall:
    - location: scripts/inicio.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/permissao.sh
      timeout: 30
      runas: root